#! /bin/bash 

##################################################################################
# This script will check all File systems and compare their threshold            #
# to the threshold level that you will type in the beginning of the script.      #
# Keep in mind that the script will create a file in /home directory             #
# and fill it with the output of the utilized file systems (the biggest files)   #
# This activity will take some additional free space on your system.             #
# Next step, you will be prompted to answer wether you would like the log files  #
# to be compressed or not. Before answering remember that this will create new   #
# file in the same directory which will take additional free space and inode,    #
# will be assighned to the file. The old file will be truncated. Keep in mind    #
# that if the FS is 100% utilized the compression migh not finnish succsessfully #
##################################################################################
 
 > /home/UtilizedFS.log

echo "Choose threshold percentege %"
read num_threshold

array=$(df -h | awk '{ print $6 }' | tail -n +2)

    for Mount_point in ${array[@]}
        do

currentFsUtil=$(df -h /$Mount_point | awk '{ print $5 }' | tail -n +2 | cut -d "%" -f 1)

echo " "
        if [[ currentFsUtil -le num_treshhold ]]

            then
                echo "filesystem mounted on $Mount_point is okay and current utilization is $currentFsUtil %"
            else
                echo "filesystem mounted on $Mount_point is above the treshhold $currentFsUtil %"
                echo " " >> /home/UtilizedFS.log 
                echo "Here are the biggest files in File system $Mount_point:" >> /home/UtilizedFS.log
                cd /$Mount_point && find . -xdev -type f -size +10M -exec  ls -lah {} \; 2>/dev/null |sort -nr -k5 | tail -20 >> /home/UtilizedFS.log
                echo "Please find the biggest files from File system $Mount_point here /home/UtilizedFS.log"
        fi
    done

################################ Compressing part ################################

log_files=$(cat /home/UtilizedFS.log | grep "^-" | grep ".log$" | awk -F " " '{print $9}' | cut -c 2-) 
    for file in ${log_files[@]}
        do
            echo -e "\n\nPlese check the type of this file:" 
            file $file 
            echo -e "\nWhould you like to compress this file (yes/no) ?"
            read answer 

                if [[ $answer == "yes" ]]
                    then
                        echo -e "\nEntering directory:" 
                        cd | dirname $file
                        gzip -v9c $file>$file-`date +%Y%m%d`.gz && >$file
                            
                            {
                            if [ $? -eq 0 ]; then 
                                echo -e "\nThe file was succssesfully compressed. You can find it under the same directory."
                                    else 
                                echo -e "\nFail, something went wrong with the compressing!"
                            fi
                            }
                                                
                    else 
                        echo -e "\nOk :)\n"
                    fi
        done  

################################ End of script ################################
