#! /bin/bash

########################################################
# This script is created in order to automate the      #
# memory management on the system. Keep in mind that   #
# if the memory is exausted, a text file will be       #
# created under /var/log directory and this will       #
# take some additional free space. Also this script    #
# will request the kernel to drop as much clean cached #
# data as possible without any system interuption.     #
########################################################

echo "What is the memory threshold level in % ?"
read number 

mem_usage=$(free | awk '/Mem/{print($3/$2)*100}' | cut -d "." -f 1)
/usr/bin/sync; echo 1 > /proc/sys/vm/drop_caches 

    if [[ "$mem_usage" -ge "$number" ]]

        then 
            touch /var/log/MemProc.log && ps -eo vsz,uid,pid,ruser,args,user,time,etime,comm | sort -r -n -k1 | head -15 > /var/log/MemProc.log

            echo "Memory usage is too high, please find the top 15 consuming processes in file with path /var/log/MemProc.log"

            dmesg -T | grep -i 'out of memory'

        else 

            echo "Memory is currently under the threshold"

    fi
###################### End of script ######################
