#! /bin/bash 

###################################################################
# This script is created in order to automate the user creation.  #
# After creating the user you will be asked do you like to ad him # 
# to the wheel group, keep in mind that this will gave him admin  #
# rights over the system ! The "mvr" string is for example of     #
# initials of a organization.                                     #
###################################################################

echo -e "\nType in employee's first name with lowercases"
read firstname
echo -e "\nType in employee's surname with lowercases"
read surname
echo -e "\nHere is the new user's generated name: mvr${firstname:0:2}${surname:4:6}\n" 

systemusers=$(cat /etc/passwd | awk -F: '{print $1}')
username_generator="mvr${firstname:0:2}${surname:4:6}"

for user in ${systemusers[@]}; do
   
    if [[ $username_generator == $user ]]
        then
            echo "This user already exist in the system!"
            exit 0
    fi
done

useradd $username_generator
echo "Does $firstname needs admin rights ? Type yes/no"
read answer 
            if [[ $answer != "yes" ]]
                then 
                    exit 0
                else
                    usermod -aG wheel $username_generator
                    echo "Please be informed that user $username_generator was granted with admin rights!"
            fi                
############################# End of script #############################
